import Head from "next/head";
type Props = {};

const createPost = (props: Props) => {
  return (
    <section className="h-screen flex justify-center items-center">
      <Head>
        <title>Create Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full flex justify-center items-center ">
        <form className="flex justify-center items-center p-5 shadow-xl border flex-col gap-3 rounded-2xl">
          <label className="text-3xl">Write Whatever</label>
          <input type="text" className="w-30 h-20 border" />
          <button className="btn">Post</button>
        </form>
      </main>
    </section>
  );
};

export default createPost;
